import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { company, stats, milestones, team } from '../data/site.js'
import PageHero from '../components/PageHero.jsx'
import { Reveal, AnimatedHeading } from '../components/motion.jsx'

const principles = [
  ['01', 'Human before headline', 'Every decision begins with how a family arrives home, how a team works, and how a neighbourhood feels.'],
  ['02', 'A promise in the details', 'The quality of a place reveals itself in the things that are not immediately photographed.'],
  ['03', 'Future-minded, locally rooted', 'We make enduring spaces for the energy, weather and rhythm of western India.'],
]

export default function About() {
  return <>
    <PageHero title="A better way to grow." crumb="About Us" subtitle="A real-estate studio creating calm, considered places for life and work." image="https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=2200&q=85" />
    <section className="bg-cream-50 py-24 sm:py-36"><div className="mx-auto grid max-w-[1600px] gap-12 px-5 sm:px-8 lg:grid-cols-12"><Reveal className="lg:col-span-5"><img src="https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=1300&q=85" alt="GrowUP team collaborating" className="aspect-[4/5] h-full w-full object-cover" /></Reveal><div className="flex flex-col justify-center lg:col-span-6 lg:col-start-7"><p className="label flex items-center gap-3 text-ink-700/65"><span className="h-px w-8 bg-ink-900"/>Since 2008 / Ahmedabad</p><AnimatedHeading text="Buildings are only the beginning." className="mt-7 font-display text-6xl leading-[.82] tracking-[-.06em] sm:text-8xl" /><Reveal delay={.15}><p className="mt-9 max-w-xl text-xl leading-relaxed text-ink-700">GrowUP began with one clear belief: property should give more to everyday life. Nearly two decades later, we still shape every residence, retail space and workplace around that simple idea.</p><p className="mt-5 max-w-xl leading-relaxed text-ink-700/75">We bring together thoughtful design, transparent delivery and long-term value—so every GrowUP address feels as good to own as it does to arrive at.</p></Reveal></div></div></section>
    <section className="bg-acid py-16 sm:py-20"><div className="mx-auto max-w-[1600px] px-5 sm:px-8"><p className="label">The studio, by the numbers</p><div className="mt-10 grid gap-8 border-t border-ink-900/25 pt-7 sm:grid-cols-4">{stats.map(s => <div key={s.label}><p className="font-display text-6xl leading-none tracking-[-.075em] sm:text-7xl">{s.value}{s.suffix}</p><p className="mt-3 max-w-36 label text-ink-700">{s.label}</p></div>)}</div></div></section>
    <section className="bg-ink-900 py-24 text-cream-50 sm:py-36"><div className="mx-auto max-w-[1600px] px-5 sm:px-8"><div className="grid gap-10 lg:grid-cols-12"><div className="lg:col-span-5"><p className="label flex items-center gap-3 text-cream-50/65"><span className="h-px w-8 bg-acid"/>What guides us</p><h2 className="mt-7 font-display text-6xl leading-[.82] tracking-[-.06em] sm:text-8xl">Our work has <i className="text-acid">standards.</i></h2></div><div className="lg:col-span-6 lg:col-start-7">{principles.map(([number, title, text]) => <Reveal key={number}><div className="grid gap-4 border-t border-cream-50/20 py-7 sm:grid-cols-[4rem_1fr]"><p className="label text-acid">{number}</p><div><h3 className="font-display text-4xl leading-none tracking-[-.04em]">{title}</h3><p className="mt-4 max-w-md leading-relaxed text-cream-50/65">{text}</p></div></div></Reveal>)}</div></div></div></section>
    <section className="bg-cream-100 py-24 sm:py-36"><div className="mx-auto grid max-w-[1600px] gap-16 px-5 sm:px-8 lg:grid-cols-12"><div className="lg:col-span-4"><p className="label flex items-center gap-3 text-ink-700/65"><span className="h-px w-8 bg-ink-900"/>Our journey</p><h2 className="mt-7 font-display text-6xl leading-[.82] tracking-[-.06em]">A story in <i>steps.</i></h2></div><div className="lg:col-span-7 lg:col-start-6">{milestones.map((milestone, index) => <Reveal key={milestone.year} delay={index * .06}><div className="grid gap-4 border-t border-ink-900/20 py-6 sm:grid-cols-[8rem_1fr]"><p className="font-display text-4xl leading-none text-clay-600">{milestone.year}</p><p className="max-w-xl text-lg leading-relaxed text-ink-700">{milestone.text}</p></div></Reveal>)}</div></div></section>
    <section className="bg-cream-50 py-24 sm:py-36"><div className="mx-auto max-w-[1600px] px-5 sm:px-8"><p className="label">Leadership</p><div className="mt-10 grid gap-8 sm:grid-cols-3">{team.map((member, index) => <motion.article key={member.name} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .08 }}><img src={member.img} alt={member.name} className="aspect-[4/5] w-full object-cover grayscale transition duration-700 hover:grayscale-0"/><p className="mt-5 label text-clay-600">{member.role}</p><h3 className="mt-2 font-display text-4xl leading-none">{member.name}</h3><p className="mt-3 max-w-sm text-sm leading-relaxed text-ink-700/70">{member.bio}</p></motion.article>)}</div></div></section>
    <section className="bg-brand-950 px-5 py-20 text-cream-50 sm:px-8 sm:py-28"><div className="mx-auto flex max-w-[1600px] flex-col justify-between gap-8 sm:flex-row sm:items-end"><h2 className="max-w-2xl font-display text-6xl leading-[.82] tracking-[-.06em] sm:text-8xl">Let’s make room for what’s <i className="text-acid">next.</i></h2><Link to="/contact" className="group flex items-center gap-4 label text-acid" data-hover>Talk to the studio <span className="grid h-10 w-10 place-items-center rounded-full border border-current transition group-hover:rotate-45">↗</span></Link></div></section>
  </>
}
