import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { projects } from '../data/projects.js'
import { company, stats } from '../data/site.js'
import { Reveal, AnimatedHeading } from '../components/motion.jsx'
import EnquiryForm from '../components/EnquiryForm.jsx'

const ease = [0.16, 1, 0.3, 1]
const projectImages = [
  'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=85',
]

function Eyebrow({ children, light = false }) { return <p className={`label flex items-center gap-3 ${light ? 'text-cream-50/65' : 'text-ink-700/70'}`}><span className={`h-px w-8 ${light ? 'bg-acid' : 'bg-ink-900'}`} />{children}</p> }
function Arrow() { return <span className="grid h-10 w-10 place-items-center rounded-full border border-current transition duration-500 group-hover:rotate-45 group-hover:bg-acid group-hover:text-ink-900">↗</span> }

function Hero() { return <section className="relative min-h-[100svh] overflow-hidden bg-ink-900 text-cream-50"><motion.div initial={{ scale: 1.07 }} animate={{ scale: 1 }} transition={{ duration: 1.3, ease }} className="absolute inset-0"><img src="/images/growup-hero.png" alt="A GrowUP residence at blue hour" fetchPriority="high" className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-ink-900/90 via-ink-900/40 to-transparent"/><div className="absolute inset-0 bg-gradient-to-t from-ink-900/90 via-transparent to-ink-900/20"/></motion.div><div className="relative mx-auto flex min-h-[100svh] max-w-[1600px] flex-col justify-end px-5 pb-8 pt-28 sm:px-8 sm:pb-10"><div className="mb-auto flex items-center justify-between label text-cream-50/70"><span>Est. 2008 · Ahmedabad</span><span className="hidden sm:block">Scroll to explore ↓</span></div><div className="max-w-6xl"><motion.p initial={{ opacity:0,y:20 }} animate={{ opacity:1,y:0 }} transition={{ delay:.45,duration:.7,ease }} className="label mb-5 flex items-center gap-3 text-acid"><span className="h-px w-8 bg-acid"/>A new perspective on property</motion.p><h1 className="max-w-5xl font-display text-[16vw] leading-[.77] tracking-[-.075em] sm:text-[11vw] lg:text-[9.5rem]"><span className="-mb-[.16em] block overflow-hidden pb-[.16em]"><motion.span initial={{y:'115%'}} animate={{y:0}} transition={{duration:1,ease,delay:.25}} className="block">Make room</motion.span></span><span className="-mb-[.16em] block overflow-hidden pb-[.16em]"><motion.span initial={{y:'115%'}} animate={{y:0}} transition={{duration:1,ease,delay:.38}} className="block italic text-acid">for living.</motion.span></span></h1></div><div className="mt-10 grid gap-6 border-t border-cream-50/20 pt-5 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-end"><p className="max-w-md text-sm leading-relaxed text-cream-50/72 sm:text-base">Homes and workspaces with a rare sense of proportion—where lasting materials, thoughtful light and generous green space do the talking.</p><Link to="/projects" data-hover className="group flex items-center justify-between gap-8 label text-cream-50">Explore our addresses <Arrow /></Link></div></div></section> }

function ProjectShowcase() { return <section className="bg-ink-900 py-24 text-cream-50 sm:py-32"><div className="mx-auto max-w-[1600px] px-5 sm:px-8"><div className="flex flex-wrap items-end justify-between gap-8"><div><Eyebrow light>Selected addresses / 01—06</Eyebrow><AnimatedHeading text="Places with presence." className="mt-6 max-w-3xl font-display text-6xl leading-[.82] tracking-[-.06em] sm:text-8xl" /></div><Link to="/projects" className="group hidden items-center gap-4 label text-acid lg:flex" data-hover>View all projects <Arrow /></Link></div><div className="mt-14 grid gap-4 md:grid-cols-3 lg:gap-6">{projects.slice(0,3).map((project, i) => <motion.article key={project.slug} initial={{ opacity:0, y:32 }} whileInView={{ opacity:1,y:0 }} viewport={{ once:true, amount:.2 }} transition={{ duration:.7, ease, delay:i*.08 }} className="min-w-0"><Link to={`/projects/${project.slug}`} data-hover className="group relative block min-h-[440px] overflow-hidden bg-brand-900 sm:min-h-[560px]"><img src={projectImages[i]} alt={project.name} loading="lazy" className="absolute inset-0 h-full w-full object-cover transition duration-700 ease-[cubic-bezier(0.16,1,0.3,1)] group-hover:scale-105"/><div className="image-shade absolute inset-0"/><div className="absolute inset-x-0 bottom-0 p-5 sm:p-7"><p className="label text-acid">0{i+1} / {project.type}</p><div className="mt-3 flex items-end justify-between gap-4"><div><h3 className="font-display text-4xl leading-none tracking-[-.05em] sm:text-5xl">{project.name}</h3><p className="mt-3 text-sm text-cream-50/65">{project.city}</p></div><Arrow /></div></div></Link></motion.article>)}</div><Link to="/projects" className="group mt-8 flex items-center justify-between border-t border-cream-50/20 pt-5 label text-acid lg:hidden" data-hover>View all projects <Arrow /></Link></div></section> }

function LivingStandard() { return <section className="bg-cream-50 py-24 sm:py-36"><div className="mx-auto grid max-w-[1600px] gap-12 px-5 sm:px-8 lg:grid-cols-12"><div className="lg:col-span-4"><Eyebrow>The GrowUP standard</Eyebrow><h2 className="mt-6 font-display text-6xl leading-[.82] tracking-[-.06em] sm:text-7xl">Well made.<br/><i>Well lived.</i></h2></div><div className="lg:col-span-7 lg:col-start-6"><p className="max-w-2xl text-2xl leading-[1.15] tracking-[-.035em] text-ink-700 sm:text-4xl">We believe a home should work quietly in your favour—feeling better today, and holding its value for years to come.</p><div className="mt-16 grid border-t border-ink-900/20 sm:grid-cols-2">{[['01','Light first','Plans that catch the morning and leave room for the evening.'],['02','Green by design','Landscape is not decoration. It is infrastructure for a better life.'],['03','Built to endure','Honest materials, clear documentation and a delivery promise that means something.'],['04','Local intelligence','Global standards, rooted in how Ahmedabad truly lives.']].map(([n,t,d])=><div key={n} className="border-b border-ink-900/20 py-7 sm:pr-8 sm:[&:nth-child(even)]:pl-8"><p className="label text-clay-600">{n}</p><h3 className="mt-8 text-3xl leading-none">{t}</h3><p className="mt-3 max-w-xs text-sm leading-relaxed text-ink-700/75">{d}</p></div>)}</div></div></div></section> }

function Numbers() { return <section className="overflow-hidden bg-acid py-16 sm:py-20"><div className="mx-auto max-w-[1600px] px-5 sm:px-8"><Eyebrow>A measured growth</Eyebrow><div className="mt-10 grid gap-7 border-t border-ink-900/25 pt-6 sm:grid-cols-4">{stats.map(s=><div key={s.label}><p className="font-display text-6xl leading-none tracking-[-.07em] sm:text-7xl">{s.value}{s.suffix}</p><p className="mt-3 max-w-[12rem] label text-ink-700">{s.label}</p></div>)}</div></div></section> }

function Story() { return <section className="bg-brand-950 py-24 text-cream-50 sm:py-36"><div className="mx-auto grid max-w-[1600px] gap-12 px-5 sm:px-8 lg:grid-cols-12"><div className="lg:col-span-5"><Eyebrow light>Thinking long term</Eyebrow><AnimatedHeading text="Cities should give more than they take." className="mt-8 font-display text-6xl leading-[.83] tracking-[-.06em] sm:text-8xl"/></div><div className="flex flex-col justify-end lg:col-span-5 lg:col-start-8"><p className="text-xl leading-relaxed text-cream-50/72">From water-smart landscaping to sun-conscious orientation, every GrowUP address seeks a better relationship with its neighbourhood.</p><Link to="/about" className="group mt-10 flex items-center justify-between border-y border-cream-50/20 py-5 label text-acid" data-hover>Meet the studio <Arrow /></Link></div></div></section> }

function ContactPanel() { return <section className="bg-cream-100 px-3 py-3 sm:px-5 sm:py-5"><div className="relative overflow-hidden bg-ink-900 px-5 py-20 text-cream-50 sm:px-8 sm:py-28"><div className="pointer-events-none absolute bottom-[-.12em] right-[-.04em] font-display text-[35vw] leading-none tracking-[-.1em] text-cream-50/[.04]">G</div><div className="relative mx-auto grid max-w-[1280px] gap-14 lg:grid-cols-2"><div><Eyebrow light>Let’s make a move</Eyebrow><h2 className="mt-8 max-w-xl font-display text-6xl leading-[.83] tracking-[-.06em] sm:text-8xl">Start a<br/><i className="text-acid">conversation.</i></h2><p className="mt-8 max-w-md text-cream-50/65">Tell us what you’re looking for. Our team will make the next step feel easy.</p><a href={`tel:${company.phoneHref}`} className="mt-10 inline-block label text-acid">{company.phone} ↗</a></div><div className="bg-cream-50 p-6 text-ink-900 sm:p-9"><p className="label text-ink-700/60">Private enquiry</p><div className="mt-7"><EnquiryForm compact /></div></div></div></div></section> }

export default function Home() { return <><Hero/><ProjectShowcase/><LivingStandard/><Numbers/><Story/><ContactPanel/></> }
